### ISSUE TITLE
Broken CI tests system

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [lukasz-pyrzyk/Kronos#11]
Appveyor has a problem with running unit tests. We need to fix this issue.

> System.TypeLoadException: Could not load type 'Microsoft.Extensions.PlatformAbstractions.IApplicationShutdown' from assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
>    at Xunit.Runner.Dnx.Program..ctor(IServiceProvider services)
> System.TypeLoadException: Could not load type 'Microsoft.Extensions.PlatformAbstractions.IApplicationShutdown' from assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
>    at Xunit.Runner.Dnx.Program..ctor(IServiceProvider services)
> System.TypeLoadException: Could not load type 'Microsoft.Extensions.PlatformAbstractions.IApplicationShutdown' from assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
>    at Xunit.Runner.Dnx.Program..ctor(IServiceProvider services)
> Command exited with code 1

**Comment by lukasz-pyrzyk** [comment]
Fixed in #14
